### ISSUE TITLE
请问最新版从网站导出来的Home文件夹替换案例里面的Home无法通过是什么原因？

### ISSUE THREAD

**Issue by robyle** [ant-motion/ant-motion-dva-cli-example#2]

**Comment by jljsj33** [comment]
具体是什么报错？？？

**Comment by robyle** [comment]
Failed to compile.  
编译失败，我用该项目自带的能编译通过。并且正常显示预览。
![1](https://user-images.githubusercontent.com/11662528/38488003-a41115d2-3c14-11e8-8a24-4abdda0c664f.png)
![2](https://user-images.githubusercontent.com/11662528/38488004-a45f1ae8-3c14-11e8-8533-f408471e86a1.png)

大致情况如上图截图所示。

**Comment by jljsj33** [comment]
写得很清楚啊，，，，` npm install enquire-js --save`
